import { join } from "path";
process.env.NODE_CONFIG_DIR = join(__dirname, "..", "config");

import { writeFileSync } from "fs";
import { pjrCommandFactory } from "../commands";

/**
 * Write commands markdown document
 */
function writeCommandsPage() {
  const pjr = pjrCommandFactory();
  const md = pjr.toMarkdownDoc();
  const pageToc = pjr.toTableOfContents();
  const docPath = join(__dirname, "..", "..", "docs", "commands.md");
  const mdlintDisableComment = "<!-- markdownlint-disable -->";
  const autoGeneratedComment = "<!-- THIS DOCUMENT IS AUTO-GENERATED -->";
  const doc = `${mdlintDisableComment}\n${autoGeneratedComment}\n\n# Commands\n\n${pageToc}\n\n${md}`;

  writeFileSync(docPath, doc);
}

writeCommandsPage();
