name: Markdown Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  md-check:
    name: Markdown Check
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy configuration files
      run: |
        # we use upstream naming to permit for local runs
        # the action overrides reading the default yaml filename, so we must manually copy
        cp ${GITHUB_WORKSPACE}/.pyspelling.yml ${GITHUB_WORKSPACE}/.spellcheck.yaml

    # https://github.com/marketplace/actions/markdown-link-check
    - name: Markdown links check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
      continue-on-error: true
      id: md-link-check

    # https://github.com/marketplace/actions/github-spellcheck-action
    - name: Markdown spell check
      uses: rojopolis/spellcheck-github-actions@0.5.0
      continue-on-error: true
      id: md-spell-check

    # https://github.com/marketplace/actions/problem-matcher-for-markdownlint-cli
    - name: Register markdownlint problem matcher
      uses: xt0rted/markdownlint-problem-matcher@v1
      id: md-lint-check-matcher

    # https://github.com/marketplace/actions/markdownlint-mdl-action
    - name: Markdown lint check
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'
      continue-on-error: true
      id: md-lint-check

    - name: Summarize
      run: |
        echo "Markdown check results: "
        fail=0

        echo -en "- Markdown links check:    "
        if [[ "${{steps.md-link-check.conclusion}}" == "failure" ]] || [[ "${{steps.md-link-check.outcome}}" == "failure" ]];then
          fail=1
          echo -e "\e[31mFailure"
        else
          echo -e "\e[32mSuccess"
        fi

        echo -en "- Markdown spell check:    "
        if [[ "${{steps.md-spell-check.conclusion}}" == "failure" ]] || [[ "${{steps.md-spell-check.outcome}}" == "failure" ]]; then
          fail=1
          echo -e "\e[31mFailure"
        else
          echo -e "\e[32mSuccess"
        fi

        echo -en "- Markdown lint check:    "
        if [[ "${{steps.md-lint-check.conclusion}}" == "failure" ]] || [[ "${{steps.md-lint-check.outcome}}" == "failure" ]]; then
          fail=1
          echo -e "\e[31mFailure"
        else
          echo -e "\e[32mSuccess"
        fi

        if [[ $fail -eq 1 ]]; then
          echo -e "Expand individual steps above to view specific errors."
          exit 1
        fi