name: Markdown Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  md-check:
    name: Markdown Check
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint check
      run: npm run lint
